CREATE TABLE Users45
(
id INT AUTO_INCREMENT NOT NULL,
NAME VARCHAR(20) NOT NULL,
email VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
active INT DEFAULT 0,

CONSTRAINT pk_Users45_id PRIMARY KEY(id),
CONSTRAINT uk_Users45_id UNIQUE (email)
);
INSERT INTO Users45(NAME, email,PASSWORD,active)VALUES('aadi','aadi@gmail.com','a345',0);

SELECT id,NAME,email,PASSWORD,active FROM Users45;